version: "3.8"

services:
    postgres:
        image: postgres:15
        container_name: stock_picker_postgres
        environment:
            POSTGRES_DB: stock_picker
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: dev_password_123
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7-alpine
        container_name: stock_picker_redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 3s
            retries: 5

    influxdb:
        image: influxdb:2
        container_name: stock_picker_influxdb
        environment:
            INFLUXDB_DB: stock_picker_timeseries
            INFLUXDB_ADMIN_USER: admin
            INFLUXDB_ADMIN_PASSWORD: dev_password_123
            INFLUXDB_USER: stock_picker
            INFLUXDB_USER_PASSWORD: dev_password_123
        ports:
            - "8086:8086"
        volumes:
            - influxdb_data:/var/lib/influxdb2
            - influxdb_config:/etc/influxdb2
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "influx", "ping"]
            interval: 30s
            timeout: 10s
            retries: 5

volumes:
    postgres_data:
        driver: local
    redis_data:
        driver: local
    influxdb_data:
        driver: local
    influxdb_config:
        driver: local

networks:
    default:
        name: stock_picker_network
